using DokkanDaily.Helpers;
using DokkanDaily.Models;
using DokkanDaily.Models.Enums;

namespace DokkanDaily.Constants
{
    public static class DokkanConstants
    {
        #region Link Skills
        public static IReadOnlyList<LinkSkill> LinkSkills { get => linkSkills; }
        public static IReadOnlyDictionary<string, LinkSkill> LinkSkillMap { get; }
        public static IReadOnlyDictionary<string, Category> CategoryMap { get; }

        private static readonly List<LinkSkill> linkSkills =
        [
            new("All in the Family", Tier.S),
            new("Android Assault", Tier.E),
            new("Big Bad Bosses", Tier.S),
            new("Braniacs", Tier.E),
            new("Brutal Beatdown", Tier.D),
            new("Cold Judgement", Tier.C),
            new("Experienced Fighters", Tier.A),
            new("Fear and Faith", Tier.A),
            new("Gaze of Respect", Tier.F),
            new("Godly Power", Tier.B),
            new("Golden Warrior", Tier.B),
            new("GT", Tier.A),
            new("Guidance of the Dragon Balls", Tier.B),
            new("Hero of Justice", Tier.E),
            new("Infighter", Tier.A),
            new("Infinite Regeneration", Tier.C),
            new("Legendary Power", Tier.Z),
            new("Limit-Breaking Form", Tier.D),
            new("Majin", Tier.B),
            new("Metamorphosis", Tier.D),
            new("Nightmare", Tier.A),
            new("Over in a Flash", Tier.A),
            new("Power Bestowed by God", Tier.D),
            new("Prodigies", Tier.C),
            new("Revival", Tier.F),
            new("Royal Lineage", Tier.C),
            new("Saiyan Pride", Tier.D),
            new("Saiyan Roar", Tier.B),
            new("Saiyan Warrior Race", Tier.S),
            new("Shocking Speed", Tier.S),
            new("Solid Support", Tier.E),
            new("Strongest Clan in Space", Tier.D),
            new("The Innocents", Tier.D),
            new("The Saiyan Lineage", Tier.B),
            new("The Wall Standing Tall", Tier.C),
            new("Thirst for Conquest", Tier.E),
            new("Universe's Most Malevolent", Tier.D),
            new("Warrior Gods", Tier.B),
            new("Z Fighters", Tier.E)
        ];
        #endregion

        #region Leaders
        public static IReadOnlyList<Leader> Leaders { get => leaders; }

        private static readonly List<Leader> leaders =
        [
            //super
            new("Peerless Gleam", "Super Saiyan 4 Gogeta", Tier.E),
            new("Hidden Power Unleashed", "Ultimate Gohan", Tier.E),
            new("Limitless Radiance", "Super Vegito", Tier.E),
            new("Mark of Saiyan Strength", "Super Saiyan 3 Bardock", Tier.F),
            new("Fused Fighting Force", "Super Saiyan Goku (Angel) & Super Saiyan Vegeta (Angel)", Tier.F),
            new("Fused Super Power", "Super Saiyan Goku & Super Saiyan Vegeta", Tier.F),
            new("Boiling Power", "Super Saiyan Goku", Tier.F),
            new("Miraculous Outcome", "Goku & Frieza (Final Form) (Angel)", Tier.E),
            new("Last-Ditch Battle", "Android #17", Tier.E),
            new("Absolute Power", "Jiren", Tier.F),
            new("Observance of Pride", "Super Saiyan God SS Vegeta", Tier.F),
            new("Hope-Filled Strike", "Super Full Power Saiyan 4 Goku", Tier.E),
            new("Power to Face Despair", "Super Saiyan Gohan (Future)", Tier.D),
            new("Transcendent Fusion", "Super Saiyan Gogeta", Tier.D),
            new("Limitless Combat Power", "Super Saiyan Vegeta", Tier.E),
            new("Miracle-Calling Clash", "Super Saiyan Gohan (Teen) & Super Saiyan Goten (Kid)", Tier.D),
            new("All-Or-Nothing Punch", "Goku (Youth)", Tier.E),
            new("Apex of Supreme Saiyan Power", "Super Saiyan 4 Goku", Tier.E),
            new("Unrivaled Saiyan's Peak", "Super Saiyan 4 Vegeta", Tier.E),
            new("Endless Adventure", "Goku (GT) & Pan (GT) & Trunks (GT)", Tier.D),
            new("Awakened True Power", "Super Saiyan Gohan (Youth)", Tier.E),
            new("Pinnacle of Fury", "Goku", Tier.F),
            new("Resilient Will to Protect the Future", "Trunks (Teen) (Future)", Tier.D),
            new("Final Super Power", "Super Saiyan God SS Goku (Kaioken)", Tier.D),
            new("Kami and Demon King United", "Piccolo", Tier.F),
            new("Heroic Warrior", "Gohan (Future)", Tier.C),
            new("Raging Counterattack", "Bardock", Tier.F),
            new("Indomitable Fighting Spirit", "Super Saiyan 2 Vegeta", Tier.B),
            new("Rousing Fighting Spirit", "Super Saiyan 2 Goku (Angel)", Tier.B),
            new("Hot-Blooded God of Destruction", "Beerus", Tier.C),
            new("Ultimate and Invincible Fusion", "Vegito", Tier.B),
            new("Ultimate and Supreme Fusion", "Gogeta", Tier.C),
            new("Transcendent Height", "Kefla", Tier.D),
            new("Fused Hope", "Goku & Vegeta (Angel)", Tier.B),
            new("A Promise Made to Kakarot", "Super Saiyan 2 Vegeta (Angel)", Tier.B),
            new("Power Beyond the Extremes", "Gohan (Teen)", Tier.B),
            new("Astounding Fusion Power", "Gotenks", Tier.D),
            new("Beyond Boundless Power", "Super Saiyan God SS Goku (Kaioken) & Super Saiyan God SS Evolved Vegeta", Tier.B),
            new("Earth-Protecting Flash", "Super Saiyan 2 Gohan (Youth)", Tier.B),
            new("Majesty of the Mighty", "Jiren (Full Power)", Tier.C),
            new("Peerless Super Power", "Super Saiyan 4 Gogeta", Tier.A),
            new("Righteous Otherworld Defense", "Paikuhan", Tier.B),
            new("Battle to Reach the Top", "Super Saiyan Vegeta (GT)", Tier.A),
            new("Battle to Become the Strongest", "Super Saiyan Goku (GT)", Tier.A),
            new("Pint-Sized Super Warriors", "Super Saiyan Trunks (Kid) & Super Saiyan Goten (Kid)", Tier.C),
            new("True Warrior Race", "Super Saiyan God SS Evolved Vegeta", Tier.A),
            new("True Ultra Instinct", "Goku (Ultra Instinct)", Tier.A),
            new("Universe 7's All-Out Offensive", "Android #17 (Team Universe 7)", Tier.B),
            new("Ally of Love and Friendship", "Videl", Tier.C),
            new("Strike of Full Anger", "Super Saiyan Goku", Tier.A),
            new("The Power to Protect", "Gohan (Kid)", Tier.A),
            new("Fusion Reborn", "Goku (Angel) & Vegeta (Angel)", Tier.B),
            new("Miracle of Friendship", "Caulifla & Kale", Tier.E),
            new("Tenacious Secret Plan", "Super Vegeta", Tier.D),
            new("Remaining Hope", "Super Saiyan Gohan (Future) & Trunks (Youth) (Future)/Super Saiyan Gohan (Future)", Tier.A),
            new("Fate-Changing Messenger", "Trunks (Teen)", Tier.B),
            new("Battle to Protect Tomorrow", "Super Saiyan 2 Goku", Tier.A),
            new("Warriors Entrusted with Earth's Fate", "Super Saiyan Goku/Super Saiyan Gohan (Youth)", Tier.A),
            new("Desperate Onslaught", "Goku & Piccolo/Piccolo", Tier.B),
            new("Saiyan Warriors with Ultimate Power", "Super Saiyan 4 Goku & Super Saiyan 4 Vegeta", Tier.S),
            new("Divine Warriors with Infinite Power", "Super Saiyan God Goku & Super Saiyan God Vegeta", Tier.S),
            new("Battle Against Limits", "Goku (Kaioken)", Tier.A),
            new("Extraordinary Super Warrior", "Super Saiyan Goku", Tier.C),
            new("Full-Power Final Showdown", "Super Saiyan Goku & Super Saiyan Vegeta", Tier.E),
            new("Stamina to Attack Evil", "Pan (GT)", Tier.B),
            new("Fearless Hero", "Gamma 2", Tier.A),
            new("Imperturbable Hero", "Gamma 1", Tier.A),
            new("Divine Combat Begins", "Super Saiyan God SS Goku/Super Saiyan God SS Vegeta", Tier.A),
            new("Power of Pride and Hope", "Super Saiyan God SS Vegeta & Super Saiyan Trunks (Future)", Tier.S),
            new("Exploding Latent Power", "Piccolo (Power Awakening)", Tier.S),
            new("Awakened Super Hero", "Ultimate Gohan", Tier.S),
            new("Quest for the Dragon Balls", "Goku (Youth)", Tier.B),
            new("Earth-Shaking Immense Power", "Super Saiyan Goku", Tier.B),
            new("Battle Against the Fate of Annihilation", "Bardock", Tier.F),
            new("Fighter Entrusted with Allies' Wishes", "Super Saiyan God Goku", Tier.A),
            new("Earth's Dominant Elite", "Yamcha", Tier.A),
            new("Showdown for the World's Strongest", "Goku", Tier.B),
            new("Miracle-Making Final Showdown", "Goku (GT) & Super Saiyan 4 Vegeta", Tier.S),
            new("Universe's Last Hope", "Super Saiyan 3 Goku & Super Saiyan 2 Vegeta", Tier.S),
            new("A Soul Pumped Up in Battle", "Goku", Tier.S),
            new("Beyond the Shining Clouds", "Gohan (Kid)", Tier.A),
            new("Resilient Power of Emotions", "Kale (Berserk)", Tier.C),
            new("All-Out Final Battle", "Super Saiyan God SS Goku & Super Saiyan God SS Vegeta", Tier.A),
            new("Indomitable Fighter", "Super Saiyan Gohan (Future)", Tier.A),
            new("Hope at the End of a Deadly Showdown", "Super Saiyan Trunks (Future)", Tier.C),
            new("Greatest Evolution of Power", "Super Saiyan 4 Goku", Tier.B),
            new("Genius Scientist's Courage and Resolve", "Android #21 (Normal)", Tier.D),
            new("All-Out Ultimate Battle", "Super Saiyan Goku & Super Saiyan Vegeta & Super Saiyan Trunks (Teen)", Tier.A),
            new("Super Power Counterattack", "Super Saiyan Trunks (Teen)", Tier.E),
            new("Intense Struggle for Survival", "Androids #17 & #18", Tier.B),
            new("Epic Defensive Battle", "Piccolo & Gohan (Kid)/Gohan (Kid)", Tier.C),
            new("Exploding Fist", "Super Saiyan 3 Goku", Tier.B),
            new("Pressed-for-Time Showdown", "Super Saiyan 3 Goku (Angel)", Tier.A),
            new("Scattered Reflection of Overflowing Fighting Spirit", "Super Saiyan Gogeta", Tier.B),
            new("Radiantly Shining Heroes", "Gamma 1 & Gamma 2/Gamma 1", Tier.A),
            new("Newfound Power Beyond the Ultimate", "Gohan (Beast)", Tier.A),
            new("Transcendent Divine Power", "Goku (Ultra Instinct -Sign-)", Tier.B),
            new("Determination to Protect Universe 11", "Toppo", Tier.C),
            new("Fierce Clash of Burning Power", "Super Saiyan Goku & Super Saiyan Gohan (Youth) & Super Saiyan Trunks (Teen)", Tier.S),
            new("All-Out Super Attack", "Super Saiyan Gohan (Teen)", Tier.A),
            new("Next-Generation-Guiding Turtle School", "Master Roshi", Tier.B),
            new("Audacious Finish", "Super Saiyan 3 Gotenks", Tier.A),
            new("Solitary Iron Wall of Power", "Jiren", Tier.A),
            new("Battle for the Dragon Balls in the Demon Realm", "Super Saiyan Goku (Mini) (DAIMA)", Tier.A),
            new("Wielder of Thunder Magic", "Glorio", Tier.S),
            new("Fight to Protect Pride and Keep Oaths", "Super Saiyan God SS Evolved Vegeta", Tier.A),
            new("Incomparable Radiance", "Super Saiyan Goku + Super Saiyan Vegeta (Angel)", Tier.S),
            new("Ultimate Saiyan Power Roar", "Super Saiyan 3 Goku (GT) (Golden Giant Ape)", Tier.B),
            new("Unprecedented Miracle", "Super Saiyan Vegeta (Angel) + Super Saiyan Goku (Angel)", Tier.S),
            new("Fighter Entrusted with Fate", "Super Saiyan 2 Gohan (Youth)", Tier.S),
            new("Thoroughly Refined Strength", "Super Saiyan 3 Vegeta (Mini) (DAIMA)", Tier.S),
            new("Exciting and Heart-Pounding Adventure", "Goku (Youth)", Tier.S),
            new("Unpredictable Powerful Technique", "Paikuhan", Tier.B),
            new("Ceaseless Combat", "Super Saiyan God SS Goku (Kaioken)", Tier.A),
            new("The Perfect Duo", "Super Saiyan 2 Caulifla + Super Saiyan 2 Kale", Tier.B),
            new("Furious Final Battle in the Future", "Super Saiyan God SS Goku + Super Saiyan God SS Vegeta", Tier.Z),
            new("Fighter of Ultimate Radiance", "Super Saiyan 4 Gogeta", Tier.S),
            new("Spirited New Generation", "Super Saiyan Gohan (Teen) + Super Saiyan Trunks (Kid) & Super Saiyan Goten (Kid)", Tier.A),
            new("Spirited Showdown", "Super Saiyan 4 Goku (Mini) (DAIMA)", Tier.Z),
            new("Bonds Leading to the Future", "Super Saiyan Gohan (Future)/Super Saiyan Trunks (Youth) (Future)", Tier.S),
            new("Cooperation for Justice", "Ultimate Gohan + Gamma 1", Tier.S),
            new("Alliance of Justice", "Gamma 2 + Piccolo (Power Awakening)", Tier.S),
            new("Maximum-Power Battle", "Super Saiyan 4 Goku (DAIMA)", Tier.Z),
            new("Earth-Shattering Climax", "Super Saiyan 3 Vegeta (DAIMA)", Tier.S),
            new("Challenging the Strongest of the Strong", "Goku (Ultra Instinct -Sign-) + Super Saiyan God SS Evolved Vegeta", Tier.S),
            new("Final Showdown Against the Shadow Dragons", "Super Saiyan 4 Vegeta + Super Saiyan 4 Goku", Tier.Z),
            new("Breakthrough Amidst Adversity", "Piccolo", Tier.A),
            new("Overwhelming Force of Destruction", "Beerus", Tier.S),
            new("Epic Battle of Divine Scale", "Super Saiyan God Goku", Tier.Z),
            //extreme
            new("Crashing Maelstrom", "Omega Shenron", Tier.E),
            new("Emperor's True Splendor", "Golden Frieza (Angel)", Tier.F),
            new("Explosive Evolution", "Turles", Tier.F),
            new("Assassin's Ultimate Technique", "Hit", Tier.F),
            new("Shocking Absorption Ability", "Buu (Super)", Tier.E),
            new("Endless Evolution of the Warrior Race", "Super Saiyan Broly", Tier.F),
            new("Fusion with the Big Gete Star", "Metal Cooler", Tier.F),
            new("Epitome of Sublime Beauty", "Goku Black", Tier.F),
            new("The True Value of Perfect Form", "Cell (Perfect Form)", Tier.E),
            new("The Androids' Journey", "Androids #17 & #18/Android #16", Tier.D),
            new("True Power of a God", "Zamasu", Tier.D),
            new("Extreme Ultimate Power", "Cooler", Tier.F),
            new("Foe Elimination Circuit", "Android #13", Tier.F),
            new("Invincible Absorption", "Majin Buu (Gotenks)", Tier.C),
            new("Split Into Good and Evil", "Majin Buu (Good)/Majin Buu (Pure Evil)", Tier.C),
            new("Murderous Overlord", "Boujack", Tier.C),
            new("Instinctive Destruction", "Legendary Super Saiyan Broly", Tier.C),
            new("Otherworld in Collapse", "Janemba", Tier.A),
            new("Ceremony of Revenge", "Super #17", Tier.S),
            new("Roar of Resentment", "Frieza (Full Power)", Tier.B),
            new("Transcendent Light-Speed Battle Erupts", "Hit & Super Saiyan God Goku", Tier.B),
            new("Boiling Evil", "Super Janemba", Tier.B),
            new("Game of Death", "Androids #17 (Future) & #18 (Future)", Tier.B),
            new("Brief Paternal Moment", "Majin Vegeta", Tier.C),
            new("Majin of Destruction", "Buu (Kid)", Tier.C),
            new("Ultimate Life Form with Immense Power", "Cell (1st Form)", Tier.C),
            new("Captain's Ace in the Hole", "Captain Ginyu", Tier.C),
            new("Furious Last Resort", "Vegeta (Giant Ape)", Tier.A),
            new("Unveiling of Power", "Raditz", Tier.A),
            new("Planet-Crushing Blow", "Cooler (Final Form)", Tier.E),
            new("Infinite Terror", "Metal Cooler", Tier.E),
            new("Dawn of an Ideal World", "Fusion Zamasu", Tier.A),
            new("Emperor's Newfound Power", "Golden Frieza", Tier.B),
            new("Death Match for World Domination", "Piccolo Jr. (Giant Form)", Tier.C),
            new("Evil-Stained Androids", "Android #17 & Hell Fighter #17", Tier.F),
            new("Infinite Sanctuary", "Fusion Zamasu", Tier.B),
            new("Demonic Fighter Wielding Forbidden Power", "Turles", Tier.E),
            new("The Ultimate Shadow Dragon", "Omega Shenron", Tier.A),
            new("Mastery of the Power of Rage", "Goku Black (Super Saiyan Rosé)", Tier.B),
            new("Awakening of the Prince", "Vegeta", Tier.B),
            new("Terrifying Phantom Majin", "Hirudegarn", Tier.C),
            new("The Awakened Ego and Joy of Combat", "Majin Buu (Good)", Tier.B),
            new("Beautiful Final View", "Frieza (1st Form)", Tier.C),
            new("Surge of Heightened Fighting Spirit", "Super Saiyan Broly", Tier.B),
            new("Universe-Devastating Combat Power", "Broly", Tier.A),
            new("Super Warrior Who Destroys All", "Legendary Super Saiyan Broly", Tier.A),
            new("Decisive Strike of Rebellion", "Vegeta", Tier.C),
            new("Terrifying Super Namekian", "Lord Slug", Tier.A),
            new("Application of Skills and Intelligence", "Majin Buu (Ultimate Gohan)", Tier.B),
            new("Universe 7's Final Will to Fight", "Frieza (Final Form) (Angel) + Goku", Tier.A),
            new("Final Battle at the Highest Level", "Cell (Perfect Form)", Tier.B),
            new("Counterattack in the Form of Improvement", "Hit", Tier.S),
            new("Top-Notch Assassin Skills", "Mercenary Tao", Tier.A),
            new("Crane School's True Strength", "Tien", Tier.A),
            new("Terrifying Zero Mortals Plan", "Goku Black (Super Saiyan Rosé) + Zamasu", Tier.A),
            new("World Shrouded in Evil Power", "Omega Shenron", Tier.Z),
            new("Stirred Battle Instincts", "Golden Frieza + Gogeta", Tier.S),
            new("Relentlessly Surging Power", "Broly (Wrathful)", Tier.S),
            new("Newborn Tuffle's Super Power", "Super Baby 1", Tier.S),
            new("Omen of Destruction", "SS Gohan Possessed (GT) & SS Goten Possessed (GT)", Tier.B),
            new("Threat of the Third Eye", "Third Eye Gomah", Tier.S),
            new("Response to Emergencies", "Android #16", Tier.A),
            new("Battle to Resurrect the Majin", "Dabura", Tier.S),
            new("Fated Showdown", "Majin Vegeta + Super Saiyan 2 Goku (Angel)", Tier.Z),
            new("Inconceivable Saiyan Power", "Vegeta + Nappa", Tier.S),
            new("Super Saiyan God of Successive Mutations", "Super Saiyan God Vegeta (Ultra Supervillain)", Tier.S),
        ];
        #endregion

        #region Events
        public static IReadOnlyList<string> Events { get => events; }
        private static readonly List<string> events;

        public static IReadOnlyList<Stage> Stages { get => stages; }

        private static readonly List<Stage> stages =
        [
            //new("When Wishes Backfire! Birth of the Shadow Dragons", Tier.F, "ShadowDragons"),
            //new("When Wishes Backfire! Birth of the Shadow Dragons", Tier.E, "ShadowDragons", 6),
            //new("When Wishes Backfire! Birth of the Shadow Dragons", Tier.E, "ShadowDragons", 7),
            //new("When Wishes Backfire! Birth of the Shadow Dragons", Tier.D, "ShadowDragons", 8),
            new("When Wishes Backfire! Birth of the Shadow Dragons", Tier.S, "ShadowDragons", 9),
            new("Fighting Legend: Frieza", Tier.F, "LFE"),
            new("Tremble with Fear! The Devil Awakens", Tier.C, "DevilAwakens", 1),
            new("Tremble with Fear! The Devil Awakens", Tier.C, "DevilAwakens", 2),
            //new("Tremble with Fear! The Devil Awakens", Tier.E, "DevilAwakens", 3),
            //new("Supreme Magnificent Battle [Movie Edition]", Tier.D, "SMB_MOVIE", 1),
            new("Supreme Magnificent Battle [Movie Edition]", Tier.C, "SMB_MOVIE", 2),
            new("Supreme Magnificent Battle [Movie Edition]", Tier.C, "SMB_MOVIE", 3),
            new("Supreme Magnificent Battle [Movie Edition]", Tier.B, "SMB_MOVIE", 4),
            new("Supreme Magnificent Battle [Movie Edition]", Tier.B, "SMB_MOVIE", 5),
            new("Supreme Magnificent Battle [Movie Edition]", Tier.B, "SMB_MOVIE", 6),
            new("Supreme Magnificent Battle [Movie Edition]", Tier.B, "SMB_MOVIE", 7),
            new("Supreme Magnificent Battle [Universe Survival Saga]", Tier.C, "SMB_USS", 1),
            new("Supreme Magnificent Battle [Universe Survival Saga]", Tier.B, "SMB_USS", 2),
            new("Supreme Magnificent Battle [Universe Survival Saga]", Tier.B, "SMB_USS", 3),
            new("Supreme Magnificent Battle [Universe Survival Saga]", Tier.B, "SMB_USS", 4),
            new("Supreme Magnificent Battle [Universe Survival Saga]", Tier.B, "SMB_USS", 5),
            new("Supreme Magnificent Battle [Universe Survival Saga]", Tier.A, "SMB_USS", 6),
            //new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.D, "SMB_DBS", 1),
            //new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.D, "SMB_DBS", 2),
            //new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.D, "SMB_DBS", 3),
            new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.B, "SMB_DBS", 4),
            new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.D, "SMB_DBS", 5),
            new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.D, "SMB_DBS", 6),
            new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.A, "SMB_DBS", 7),
            new("Supreme Magnificent Battle [Dragon Ball Super Edition]", Tier.A, "SMB_DBS", 8),
            new("Ultimate Red Zone [Majin Buu Saga]", Tier.D, "MBS_RZ", 1),
            new("Ultimate Red Zone [Majin Buu Saga]", Tier.B, "MBS_RZ", 2),
            new("Ultimate Red Zone [Majin Buu Saga]", Tier.B, "MBS_RZ", 3),
            new("Ultimate Red Zone [Majin Buu Saga]", Tier.A, "MBS_RZ", 4),
            new("Divine Wrath and Mortal Will", Tier.C, "DWMW", 7),
            new("Divine Wrath and Mortal Will", Tier.C, "DWMW", 8),
            new("Divine Wrath and Mortal Will", Tier.C, "DWMW", 9),
            new("Divine Wrath and Mortal Will", Tier.S, "DWMW", 10),
            new("Divine Wrath and Mortal Will", Tier.S, "DWMW", 11),
            //new("Ultimate Red Zone [Movie Edition 2]", Tier.F, "MOVIE2_RZ", 1),
            //new("Ultimate Red Zone [Movie Edition 2]", Tier.E, "MOVIE2_RZ", 2),
            //new("Ultimate Red Zone [Movie Edition 2]", Tier.E, "MOVIE2_RZ", 3),
            new("Ultimate Red Zone [Movie Edition 2]", Tier.E, "MOVIE2_RZ", 4),
            new("Ultimate Red Zone [Movie Edition 2]", Tier.E, "MOVIE2_RZ", 5),
            new("Ultimate Red Zone [Movie Edition 2]", Tier.D, "MOVIE2_RZ", 6),
            new("Ultimate Red Zone [Movie Edition 2]", Tier.D, "MOVIE2_RZ", 7),
            //new("Ultimate Red Zone [Movie Edition]", Tier.F, "MOVIE_RZ", 3),
            //new("Ultimate Red Zone [Movie Edition]", Tier.F, "MOVIE_RZ", 4),
            //new("Ultimate Red Zone [Movie Edition]", Tier.F, "MOVIE_RZ", 5),
            //new("Ultimate Red Zone [Movie Edition]", Tier.F, "MOVIE_RZ", 6),
            //new("Ultimate Red Zone [Movie Edition]", Tier.E, "MOVIE_RZ", 7),
            //new("Ultimate Red Zone [Movie Edition]", Tier.C, "MOVIE_RZ", 8),
            new("10th Anniv.! Anniversary Battle", Tier.A, "ANNI", 14),
            new("10th Anniv.! Anniversary Battle", Tier.A, "ANNI", 15),
            new("10th Anniv.! Anniversary Battle", Tier.A, "ANNI", 16),
            new("10th Anniv.! Anniversary Battle", Tier.A, "ANNI", 17),
            //new("Ultimate Red Zone [Dismal Future Edition]", Tier.E, "DF_RZ", 1),
            //new("Ultimate Red Zone [Dismal Future Edition]", Tier.E, "DF_RZ", 2),
            //new("Ultimate Red Zone [Dismal Future Edition]", Tier.D, "DF_RZ", 3),
            //new("Ultimate Red Zone [Dismal Future Edition]", Tier.D, "DF_RZ", 4),
            new("Ultimate Red Zone [Dismal Future Edition]", Tier.C, "DF_RZ", 5),
            //new("Ultimate Red Zone [Wicked Bloodline Edition]", Tier.F, "WB_RZ", 1),
            //new("Ultimate Red Zone [Wicked Bloodline Edition]", Tier.F, "WB_RZ", 2),
            //new("Ultimate Red Zone [Wicked Bloodline Edition]", Tier.F, "WB_RZ", 3),
            //new("Ultimate Red Zone [Wicked Bloodline Edition]", Tier.F, "WB_RZ", 4),
            //new("Ultimate Red Zone [Wicked Bloodline Edition]", Tier.E, "WB_RZ", 5),
            //new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.C, "MB_ME", 1),
            //new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.C, "MB_ME", 2),
            //new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.C, "MB_ME", 3),
            //new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.C, "MB_ME", 4),
            new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.C, "MB_ME", 5),
            new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.C, "MB_ME", 6),
            new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.B, "MB_ME", 7),
            new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.B, "MB_ME", 8),
            new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.A, "MB_ME", 9),
            new("Dragon Ball Z: Memorable Battles [Movie Edition]", Tier.A, "MB_ME", 10),
            new("Fearsome Activation! Cell Max", Tier.C, "CELLMAX", 1),
            new("Fearsome Activation! Cell Max", Tier.A, "CELLMAX", 2),
            new("Dragon Ball Super: Memorable Battles [Movie Edition]", Tier.C, "MB_ME_DBS", 1),
            new("Dragon Ball Super: Memorable Battles [Movie Edition]", Tier.C, "MB_ME_DBS", 2),
            new("Dragon Ball Super: Memorable Battles [Movie Edition]", Tier.B, "MB_ME_DBS", 3),
            new("Dragon Ball Super: Memorable Battles [Movie Edition]", Tier.B, "MB_ME_DBS", 4),
            new("Heart-Pounding Heroine Battle", Tier.F, "PinkZone", 3),
            new("Heart-Pounding Heroine Battle", Tier.D, "PinkZone", 6),
            new("Heart-Pounding Heroine Battle", Tier.E, "PinkZone", 8),
            new("Epic! Transcendent! Gods of Destruction Assemble", Tier.C, "GOD", 13),
            new("Epic! Transcendent! Gods of Destruction Assemble", Tier.C, "GOD", 14),
            new("Epic! Transcendent! Gods of Destruction Assemble", Tier.C, "GOD", 15),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.B, "VEGETA_RZ"),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.A, "VEGETA_RZ", 2),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.A, "VEGETA_RZ", 3),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.A, "VEGETA_RZ", 4),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.A, "VEGETA_RZ", 5),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.A, "VEGETA_RZ", 6),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.A, "VEGETA_RZ", 7),
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.S, "VEGETA_RZ", 8), 
            new("Ultimate Red Zone [Vegeta's Story Edition]", Tier.S, "VEGETA_RZ", 9),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.B, "GOKU_RZ"),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.A, "GOKU_RZ", 2),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.A, "GOKU_RZ", 3),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.A, "GOKU_RZ", 4),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.A, "GOKU_RZ", 5),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.A, "GOKU_RZ", 6),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.A, "GOKU_RZ", 7),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.S, "GOKU_RZ", 8),
            new("Ultimate Red Zone [Goku's Story Edition]", Tier.S, "GOKU_RZ", 9),
            //new("Supreme Magnificent Battle [Gathering of Super Warriors Edition]", Tier.E, "SMB_GSW"),
            //new("Supreme Magnificent Battle [Gathering of Super Warriors Edition]", Tier.E, "SMB_GSW", 2),
            new("Supreme Magnificent Battle [Gathering of Super Warriors Edition]", Tier.E, "SMB_GSW", 3),
            new("Supreme Magnificent Battle [Gathering of Super Warriors Edition]", Tier.D, "SMB_GSW", 4),
            new("Supreme Magnificent Battle [Gathering of Super Warriors Edition]", Tier.A, "SMB_GSW", 5),
            new("Supreme Magnificent Battle [Gathering of Super Warriors Edition]", Tier.A, "SMB_GSW", 6),
            new("Ultimate Red Zone [DB Saga]", Tier.C, "OG_DB_RZ"),
            new("Ultimate Red Zone [DB Saga]", Tier.B, "OG_DB_RZ", 2),
            new("Ultimate Red Zone [DB Saga]", Tier.B, "OG_DB_RZ", 3),
            new("Ultimate Red Zone [DB Saga]", Tier.B, "OG_DB_RZ", 4),
            new("Ultimate Red Zone [DB Saga]", Tier.B, "OG_DB_RZ", 5),
            new("Ultimate Red Zone [DB Saga]", Tier.A, "OG_DB_RZ", 6),
            new("Global Campaign! Special Battle 2025", Tier.ZPlus, "SB25"),
            new("Global Campaign! Special Battle 2025", Tier.Z, "SB25", 2),
            new("Global Campaign! Special Battle 2025", Tier.Z, "SB25", 3),
            new("Global Campaign! Special Battle 2025", Tier.Z, "SB25", 4),
            //new("Seriously Serious! All-Out Battles", Tier.C, "Serious"),
            //new("Seriously Serious! All-Out Battles", Tier.C, "Serious", 2),
            //new("Seriously Serious! All-Out Battles", Tier.C, "Serious", 3),
            //new("Seriously Serious! All-Out Battles", Tier.C, "Serious", 4),
            new("Seriously Serious! All-Out Battles", Tier.A, "Serious", 5),
            new("Seriously Serious! All-Out Battles", Tier.A, "Serious", 6),
            new("Seriously Serious! All-Out Battles", Tier.S, "Serious", 7),
            new("Seriously Serious! All-Out Battles", Tier.A, "Serious", 8),
            new("Seriously Serious! All-Out Battles", Tier.S, "Serious", 9),
            new("Perfect Cooperation! Team Battle", Tier.C, "PCTB"),
            new("Perfect Cooperation! Team Battle", Tier.B, "PCTB", 2),
            new("Perfect Cooperation! Team Battle", Tier.A, "PCTB", 3),
            new("Perfect Cooperation! Team Battle", Tier.A, "PCTB", 4),
            new("Perfect Cooperation! Team Battle", Tier.A, "PCTB", 5),
            new("Perfect Cooperation! Team Battle", Tier.S, "PCTB", 6),
            new("Perfect Cooperation! Team Battle", Tier.S, "PCTB", 7),
            new("Supreme Magnificent Battle [Next-Generation Saiyans Edition]", Tier.Z, "SMB_NGS"),
            new("Supreme Magnificent Battle [Next-Generation Saiyans Edition]", Tier.ZPlus, "SMB_NGS", 2),
            new("Supreme Magnificent Battle [Next-Generation Saiyans Edition]", Tier.ZPlus, "SMB_NGS", 3),
            new("Supreme Magnificent Battle [Next-Generation Saiyans Edition]", Tier.ZPlus, "SMB_NGS", 4),
            new("Supreme Magnificent Battle [Next-Generation Saiyans Edition]", Tier.ZPlus, "SMB_NGS", 5),
            new("Ultimate Red Zone [DAIMA Edition]", Tier.Z, "DAIMA_RZ"),
            new("Ultimate Red Zone [DAIMA Edition]", Tier.S, "DAIMA_RZ", 2),
            new("Ultimate Red Zone [DAIMA Edition]", Tier.ZPlus, "DAIMA_RZ", 3),
            new("Ultimate Red Zone [Pure Saiyans Edition]", Tier.S, "PS_RZ"),
            new("Ultimate Red Zone [Pure Saiyans Edition]", Tier.S, "PS_RZ", 2),
            new("Ultimate Red Zone [Pure Saiyans Edition]", Tier.Z, "PS_RZ", 3),
            new("Ultimate Red Zone [Pure Saiyans Edition]", Tier.Z, "PS_RZ", 4),
            new("Ultimate Red Zone [Pure Saiyans Edition]", Tier.Z, "PS_RZ", 5),
            new("Ultimate Red Zone [Pure Saiyans Edition]", Tier.ZPlus, "PS_RZ", 6),
            new("Ultimate Red Zone [Red Ribbon Army Edition]", Tier.E, "RR_RZ"),
            new("Ultimate Red Zone [Red Ribbon Army Edition]", Tier.D, "RR_RZ", 2),
            new("Ultimate Red Zone [Red Ribbon Army Edition]", Tier.E, "RR_RZ", 3),
            new("Ultimate Red Zone [Red Ribbon Army Edition]", Tier.D, "RR_RZ", 4),
            new("Ultimate Red Zone [Red Ribbon Army Edition]", Tier.C, "RR_RZ", 5),
            new("Ultimate Red Zone [Red Ribbon Army Edition]", Tier.C, "RR_RZ", 6),
            new("Ultimate Red Zone [Artificial Life Forms Edition]", Tier.S, "ALF_RZ"),
            new("Ultimate Red Zone [Artificial Life Forms Edition]", Tier.S, "ALF_RZ", 2),
            new("Ultimate Red Zone [Artificial Life Forms Edition]", Tier.S, "ALF_RZ", 3),
            new("Ultimate Red Zone [Artificial Life Forms Edition]", Tier.ZPlus, "ALF_RZ", 4),
            new("Ultimate Red Zone [Artificial Life Forms Edition]", Tier.Z, "ALF_RZ", 5),
            new("Ultimate Red Zone [Artificial Life Forms Edition]", Tier.ZPlus, "ALF_RZ", 6),
            new("11th Anniversary! Special Battle Part 1", Tier.Z, "11_SB_P1"),
            new("11th Anniversary! Special Battle Part 1", Tier.Z, "11_SB_P1"),
            new("11th Anniversary! Special Battle Part 2", Tier.Z, "11_SB_P2"),
            new("11th Anniversary! Special Battle Part 2", Tier.ZPlus, "11_SB_P2"),
            new("Seriously Serious! All-Out Battles 2", Tier.A, "Serious2"),
            new("Seriously Serious! All-Out Battles 2", Tier.A, "Serious2", 2),
            new("Seriously Serious! All-Out Battles 2", Tier.S, "Serious2", 3),
            new("Seriously Serious! All-Out Battles 2", Tier.S, "Serious2", 4),
            new("Seriously Serious! All-Out Battles 2", Tier.A, "Serious2", 5),
        ];
        #endregion

        #region Categories
        public static IReadOnlyList<Category> Categories { get => categories; }

        private static readonly List<Category> categories =
        [
            new("Accelerated Battle", Tier.S),
            new("All-Out Struggle", Tier.A),
            new("Androids", Tier.B),
            new("Androids/Cell Saga", Tier.C),
            new("Artificial Life Forms", Tier.B),
            new("Battle of Fate", Tier.Z),
            new("Battle of Wits", Tier.E),
            new("Bond of Friendship", Tier.A),
            new("Bond of Master and Disciple", Tier.S),
            new("Bond of Parent and Child", Tier.S),
            new("Connected Hope", Tier.A),
            new("Corroded Body and Mind", Tier.A),
            new("Crossover", Tier.C),
            new("DAIMA", Tier.A),
            new("DB Saga", Tier.B),
            new("Defenders of Justice", Tier.C),
            new("Demonic Power", Tier.S),
            new("Dragon Ball Heroes", Tier.D),
            new("Earthlings", Tier.B),
            new("Earth-Bred Fighters", Tier.Z),
            new("Earth-Protecting Heroes", Tier.S),
            new("Entrusted Will", Tier.A),
            new("Exploding Rage", Tier.A),
            new("Final Trump Card", Tier.S),
            new("Full Power", Tier.A),
            new("Fused Fighters", Tier.S),
            new("Fusion", Tier.S),
            new("Future Saga", Tier.S),
            new("Giant Ape Power", Tier.S),
            new("Gifted Warriors", Tier.B),
            new("Ginyu Force", Tier.E),
            new("Goku's Family", Tier.S),
            new("GT Bosses", Tier.S),
            new("GT Heroes", Tier.S),
            new("Heavenly Events", Tier.F),
            new("Hybrid Saiyans", Tier.S),
            new("Inhuman Deeds", Tier.S),
            new("Joined Forces", Tier.B),
            new("Kamehameha", Tier.S),
            new("Legendary Existence", Tier.B),
            new("Low-Class Warrior", Tier.D),
            new("Majin Buu Saga", Tier.S),
            new("Majin Power", Tier.C),
            new("Mastered Evolution", Tier.A),
            new("Miraculous Awakening", Tier.A),
            new("Mission Execution", Tier.B),
            new("Movie Bosses", Tier.B),
            new("Movie Heroes", Tier.S),
            new("Namekians", Tier.F),
            new("Otherworld Warriors", Tier.B),
            new("Peppy Gals", Tier.D),
            new("Planet Namek Saga", Tier.D),
            new("Planetary Destruction", Tier.A),
            new("Potara", Tier.A),
            new("Power Absorption", Tier.B),
            new("Power Beyond Super Saiyan", Tier.S),
            new("Powerful Comeback", Tier.A),
            new("Power of Wishes", Tier.S),
            new("Pure Saiyans", Tier.Z),
            new("Rapid Growth", Tier.D),
            new("Realm of Gods", Tier.A),
            new("Representatives of Universe 7", Tier.A),
            new("Resurrected Warriors", Tier.F),
            new("Revenge", Tier.E),
            new("Saiyan Saga", Tier.B),
            new("Saviors", Tier.D),
            new("Shadow Dragon Saga", Tier.A),
            new("Siblings' Bond", Tier.B),
            new("Space-Traveling Warriors", Tier.C),
            new("Special Pose", Tier.D),
            new("Storied Figures", Tier.E),
            new("Successors", Tier.A),
            new("Super Bosses", Tier.A),
            new("Super Heroes", Tier.S),
            new("Super Saiyan 2", Tier.E),
            new("Super Saiyan 3", Tier.A),
            new("Super Saiyans", Tier.S),
            new("Sworn Enemies", Tier.E),
            new("Target: Goku", Tier.F),
            new("Team Bardock", Tier.F),
            new("Terrifying Conquerors", Tier.B),
            new("Time Limit", Tier.S),
            new("Time Travelers", Tier.S),
            new("Tournament Participants", Tier.A),
            new("Transformation Boost", Tier.S),
            new("Turtle School", Tier.S),
            new("Uncontrollable Power", Tier.B),
            new("Universe 6", Tier.B),
            new("Universe 11", Tier.C),
            new("Universe Survival Saga", Tier.A),
            new("Vegeta's Family", Tier.S),
            new("Wicked Bloodline", Tier.D),
            new("World Tournament", Tier.D),
            new("Worldwide Chaos", Tier.B),
            new("Worthy Rivals", Tier.B),
            new("Youth", Tier.A)
        ];
        #endregion

        #region Misc.
        private static readonly List<Unit> unitDB = [];
        public static IReadOnlyList<Unit> UnitDB { get => unitDB.AsReadOnly(); }

        public static readonly IReadOnlyDictionary<DokkanType, string> TypeHexMap = new Dictionary<DokkanType, string>()
        {
            { DokkanType.AGL, "#0555D5" },
            { DokkanType.STR, "#C4151E" },
            { DokkanType.PHY, "#B46D00" },
            { DokkanType.INT, "#883BA9" },
            { DokkanType.TEQ, "#008806" }
        }.AsReadOnly();
        public static IReadOnlyList<DailyType> DailyTypes { get; }
        #endregion

        static DokkanConstants()
        {
            LinkSkillMap = new Dictionary<string, LinkSkill>(linkSkills.Select(x => new KeyValuePair<string, LinkSkill>(x.Name, x)));
            CategoryMap = new Dictionary<string, Category>(categories.Select(x => new KeyValuePair<string, Category>(x.Name, x)));
            DailyTypes = [DailyType.Category, DailyType.Character, DailyType.LinkSkill];
            unitDB = [.. DokkanDailyHelper.BuildCharacterDb()];
            events = [.. stages
                .Select(x => x.Name)
                .Distinct()];
        }
    }
}
