name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
      - cron: '30 15 * * WED'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup dotnet'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head.ref }}
          fetch-depth: 0
          
      - name: 'Build'
        run: dotnet build
        